receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  resource:
    attributes:
      - key: deployment.environment
        value: development
        action: upsert
      - key: service.namespace
        value: verda-vida
        action: upsert

exporters:
  debug:
    verbosity: detailed
  otlp/aspire:
    endpoint: ${env:ASPIRE_ENDPOINT}
    headers:
      x-otlp-api-key: ${env:ASPIRE_API_KEY}
    tls:
        insecure: ${env:ASPIRE_INSECURE}
        insecure_skip_verify: true # Required in local development because cert is localhost and the endpoint is host.docker.internal
  otlphttp/prometheus:
    endpoint: ${env:PROMETHEUS_ENDPOINT}
    tls:
        insecure: true
  otlphttp/jaeger:
    endpoint: ${env:JAEGER_ENDPOINT}
    tls:
      insecure: true
  otlphttp/newrelic:
    endpoint: ${env:NEWRELIC_ENDPOINT}
    headers:
      api-key: ${env:NEWRELIC_API_KEY}
    tls:
      insecure: false
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/aspire, otlphttp/jaeger, otlphttp/newrelic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/aspire, otlphttp/newrelic]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - otlp/aspire
        - otlphttp/prometheus
        - otlphttp/newrelic
